In [1]:
import numpy as np
np.__version__
arr1=np.array([1,3,5,7,9])   ## any sequence like list, tuple, set, etc can be converted to numpy array
print(arr1)
print(type(arr1))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [2]:
#id() function is used to get the memory location of an object


print(f"the id of arr 1: {id(arr1)}") ##location of array in memory 
arr2=np.array([1,3,5,7,9])
print(f"the id of arr 2: {id(arr2)}") ##location of array in memory(has a different locatiojn in the memory)
arr1 is arr2 ## both are different objects in memory

the id of arr 1: 2410516271472
the id of arr 2: 2410520811376


False

In [3]:
# copying array and checking if both are same objects in memory

arr3=arr1
print(f"the id of arr 1: {id(arr1)}")
print(f"the id of arr 3: {id(arr3)}")
 ## both are same objects in memory


 #copying the array
arr4=arr1.copy()

print(f"the id of arr 4: {id(arr4)}")  ## different objects in memory


the id of arr 1: 2410516271472
the id of arr 3: 2410516271472
the id of arr 4: 2410516271184


In [4]:
#Creating arrays with different data types

#creating arrays with lists
arr5=np.array([1,3,5,7,9])
print(arr5)
print(type(arr5))

#CREATING ARRAYS WITH TUPLES
arr6=np.array((1,3,5,7,9))
print(arr6)
print(type(arr6))


#CREATING ARRAYS WITH DICTIONARIES
arr7=np.array({'one':1,'two':2,'three':3})
print(arr7)


print(type(arr7))     ## both are numpy arrays


#creating array with sets:
arr8=np.array({1,3,5,7,9})
print(arr8)
print(type(arr8))  ## it is a numpy array


#the data type of the array can be checked using the dtype attribute
print(arr8.dtype) ## the sets and the dictionaries have the data type of object whereas the list and tuple have the data type of int64


[1 3 5 7 9]
<class 'numpy.ndarray'>
[1 3 5 7 9]
<class 'numpy.ndarray'>
{'one': 1, 'two': 2, 'three': 3}
<class 'numpy.ndarray'>
{1, 3, 5, 7, 9}
<class 'numpy.ndarray'>
object


In [ ]:
#creating array with arange() function

arr9=np.arange(1,10,2)## the first argument is the starting point, the second argument is the ending point(exclusive) and the third argument is the step size
print(arr9)
print(type(arr9)) ## it is an array

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [6]:
#FINDING THE LENGTH OF THE ARRAY
print(len(arr9))   #len function is used to find the length of the array
print(arr9.size) ## size attribute is used to find the length of the array

5
5


In [7]:
arr10=np.array([333,333.333,False,'hello'])
print(arr10)
print(arr10.dtype) ## the data type of the array is object
print(type(arr10)) ## it is a numpy array

np.array([111,1.1,True]) ## the data type of the array is float64


type(arr10[0]) ## the data type of the array is a string

['333' '333.333' 'False' 'hello']
<U32
<class 'numpy.ndarray'>


numpy.str_

In [8]:
arr11=np.array(['apple','banana','cherry','date'])
print(arr11)
print(type(arr11))
print(arr11.dtype) ## the data type

['apple' 'banana' 'cherry' 'date']
<class 'numpy.ndarray'>
<U6


In [9]:
##creating arrays with linspace() method

#endpoint=True: Step size = (stop - start) / (num - 1) → Includes stop, smaller steps to fit it.
#endpoint=False: Step size = (stop - start) / num → Excludes stop, bigger steps since stop isn’t part of the array.

np.linspace(0,10,5,endpoint=True) ## the first argument is the starting point, the second argument is the ending point, the third argument is the number of elements in the array and the fourth argument is the endpoint

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
arr12=np.linspace(-10,10,20)
print(arr12)

[-10.          -8.94736842  -7.89473684  -6.84210526  -5.78947368
  -4.73684211  -3.68421053  -2.63157895  -1.57894737  -0.52631579
   0.52631579   1.57894737   2.63157895   3.68421053   4.73684211
   5.78947368   6.84210526   7.89473684   8.94736842  10.        ]


In [11]:
#creating array with zeros() function
arr13=np.zeros(5) ## the argument is the number of elements in the array
print(arr13)
print(arr13.dtype) ## the data type of the array is float64

print()
#creating arrays of ones:\
arr14=np.ones(5) ## the argument is the number of elements in the array
print(arr14)
print(arr14.dtype) ## the data type of the array is float64

[0. 0. 0. 0. 0.]
float64

[1. 1. 1. 1. 1.]
float64


In [12]:
#Multidimentional arrays

list1=[[1,2,3],[4,5,6],[7,8,9]]
arr15=np.array(list1)
print(arr15)
print(arr10[0][2])


#checking the dimentions of the array
arr15.ndim ## the ndim attribute is used to find the number of dimentions of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


2

In [ ]:
#the np.zeros() function can be used to create multidimentional arrays(always gives the numbers as a float)
arr16=np.zeros((3,3,3)) ## the argument is a tuple with the number of layers , rows and columns
print(arr16)

type(arr16[0][0][0])

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


numpy.float64

In [14]:
#to create an array of a particular data type use the keyword argument dtype
arr17=np.zeros((3,3,3),dtype=int)
print(arr17)
type(arr17[0][0][0])

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


numpy.int32

In [15]:
#to change the value to a float use the astype() method
arr18=arr17.astype(float)
print(arr18)
type(arr18[0][0][0])

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


numpy.float64

In [ ]:
#THE ATTRIBUTES OF THE NUMPY OBJECT
#shape attribute is used to find the number of rows and columns in the array
print(arr18.shape) 

#size attribute is used to find the number of elements in the array
print(arr18.size)

#dtype attribute is used to find the data type of the array
print(arr18.dtype)

#ndim attribute is used to find the number of dimentions of the array
print(arr18.ndim)

#itemsize attribute is used to find the size(in bytes) of each element in the array
print(arr18.itemsize)



(3, 3, 3)
27
float64
3
8


In [17]:
#RESHAPING THE ARRAY USING THE RESHAPE() METHOD
arr19=np.arange(1,10)
print(arr19)
print(arr19.shape)  # for one d array it returns the number  of elements in the array
print()

ARR20=arr19.reshape(3,3)
print(ARR20)
print(ARR20.shape)



[1 2 3 4 5 6 7 8 9]
(9,)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [18]:
#Random numberrs in numpy(submodule of numpy)
#rand() function is used to generate random numbers in the range of 0 to 1

arr21=np.random.rand(5)     #the numbers are generated from the uniform distribution(0 to 1)
print(arr21)

print()
arr22=np.random.randn(3,3) ## the random numbers are generated from the standard normal distribution(mean=0,standard deviation=1)
print(arr22)

[0.62825446 0.59074357 0.14480539 0.95508999 0.78865307]

[[ 1.48287685 -1.54962221  0.56657682]
 [ 0.21759083 -1.16290572  0.13334374]
 [ 0.47041656 -0.29315705 -1.78843187]]


In [19]:
#MEAN OF THE ARRAY ( both a method and a function)

arr23=np.random.randn(10000,10000)

print(arr23)
print()
print(f"the mean of the array is {arr23.mean():+5f}") ## the mean of the array is calculated using the mean() method
#else mean=np.mean(arr23)  ## the mean of the array is calculated using the mean() function



#the average is close to zero but not exactly zero because the random numbers are generated from the standard normal distribution(mean=0,standard deviation=1)
#as u increase the size of the array the mean of the array approaches zero

[[-0.73543779  0.9619233  -0.4571539  ...  0.02986879 -1.33878825
   0.81553514]
 [ 0.77011888  0.19422928 -0.55443997 ...  1.20271853 -0.69422546
   0.9539109 ]
 [ 1.42180902 -0.03384928 -0.24479813 ...  1.3339731  -1.10729208
   0.66625594]
 ...
 [-0.55621541  0.0330763   0.18591357 ...  0.20435316 -0.45000049
   0.77261423]
 [-1.12385242  0.13119749 -1.65617508 ... -0.42652836 -0.21048807
   0.03507575]
 [ 1.08569765  0.42564647  0.31565689 ... -1.5049273  -0.10545147
   1.3278108 ]]

the mean of the array is -0.000021


* the performance of the numpy array is better than the python list
* the numpy multiplies 2 to the array at once compared to the python list which multiplies 2 to each element of the list

In [20]:

%%time
for i in range(1000):
    np.arange(1000000) * 2

CPU times: total: 1.78 s
Wall time: 1.76 s


In [21]:
%%time
for i in range(1000):
    list(range(1000000)) * 2

CPU times: total: 25.7 s
Wall time: 26.5 s


In [42]:
###adding elements to the existing array

arr24=np.random.randint(1,10,5) ## the first argument is the starting point, the second argument is the ending point and the third argument is the number of elements in the array
arr25=np.append(arr24,[10,11,12]) ## the append() method is used to add elements to the array
print(arr25)
print()





arr26=np.random.randint(1,10,(3,3))
print(arr26)
print()
 ## the first argument is the starting point, the second argument is the ending point and the third argument is the shape of the array

#inserting elements to the column
arr27=np.append(arr26,[[10],[11],[12]],axis=1)  #3x1

print(arr27)

print()
#inserting elements to the row
arr28=np.append(arr26,[[10,11,12]],axis=0)  #1x3
print(arr28)

[ 4  8  9  5  2 10 11 12]

[[5 6 4]
 [3 6 7]
 [6 1 8]]

[[ 5  6  4 10]
 [ 3  6  7 11]
 [ 6  1  8 12]]

[[ 5  6  4]
 [ 3  6  7]
 [ 6  1  8]
 [10 11 12]]


In [63]:
#deleting elements from the array
arr29=np.random.randint(1,10,(4,4))
print(arr29)
print()


#the first argument is the array and the second argument is the index of the element to be deleted
arr30=np.delete(arr29,2) ## the delete() method is used to delete elements from the array 
print(arr30)

print()
print('the third row is deleted')
#deleting an entire row:
arr31=np.delete(arr29,2,axis=0) 
print(arr31)

print()
print('the third column is deleted')
#deleting an entire column:
arr32=np.delete(arr29,2,axis=1)
print(arr32)

print()
print('the original reshaped array')
print(arr29.reshape(2,8))

[[5 6 9 4]
 [6 3 8 6]
 [7 2 5 2]
 [6 1 1 3]]

[5 6 4 6 3 8 6 7 2 5 2 6 1 1 3]

the third row is deleted
[[5 6 9 4]
 [6 3 8 6]
 [6 1 1 3]]

the third column is deleted
[[5 6 4]
 [6 3 6]
 [7 2 2]
 [6 1 3]]

the original reshaped array
[[5 6 9 4 6 3 8 6]
 [7 2 5 2 6 1 1 3]]
