<h1>Indexing</h1>

In [266]:
#Indexing
#indexing in python array is like python list indexing

import numpy as np

a=np.arange(0,4)
b=np.arange(0,12).reshape(3,4)

print(a[0])

print(b[0])
print(b[0][2])


0
[0 1 2 3]
2


In [ ]:
#Using the comma operator
print(b[0,2])    # same as using print(b[0][2])

2


In [268]:
#changing the values
print(a)
a[2]=20
print(f'the array after modification is : {a}')

[0 1 2 3]
the array after modification is : [ 0  1 20  3]


Selecting multiple elements

In [269]:
#from the 1d array
#use [[]] outer bracket for indexing and inner for positions

a[[1,3,2]] #elements at pos 1,3 and 2

array([ 1,  3, 20])

In [270]:
#modifying entire Row
print(b)
b[0]=np.array([10,20,30,40])
print()
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[10 20 30 40]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [271]:
#of the 2D array
#arrayname[[row positions,.....],[column positions......]]
b[[0,2],[0,1]]  #(0,0) , (2,1)

array([10,  9])

Selecting array elements by condition

In [272]:
arr=np.random.randint(0,10,size=10)
print(arr)
print(arr[arr>3])  #elements > 3 are returned

[4 5 7 6 5 9 3 4 7 7]
[4 5 7 6 5 9 4 7 7]


In [273]:
arr[arr%2==0] ##even numbers are printed

array([4, 6, 4])

<h1>Slicing</h1>

In [274]:
#Instead of selecting one element , an range of elements in the array is specified

In [ ]:
#1D array 
# arr[start position : end position]   end is exclusive

In [276]:
arr3=np.random.randint(0,100,size=10)
print(arr3)
print(arr3[4:6])
print(arr3[:3])
print(arr[3:])

[53 62 52 31 49  9 14 85 60 51]
[49  9]
[53 62 52]
[6 5 9 3 4 7 7]


In [277]:
#Multidimensional Array:
arr4=np.random.randint(0,100,size=25).reshape(5,5)
print(arr4)
print()
print(arr4[:2])

[[56 27 48 92 13]
 [48 68 97 57 47]
 [34 12 73  3 14]
 [15 14 30  2  2]
 [37 35 60 13 84]]

[[56 27 48 92 13]
 [48 68 97 57 47]]


In [278]:
#It is also possible to slice multi dimensional arrays by crossing several indices
print(arr4[:2,1:]) # extracts the subarray consisting of the first two rows and the last four columns of the original 5x5 array.
print()
print(arr4[1,:2]) #selecting 2nd row and 2 columns

print()
print(arr4[:,:1])

[[27 48 92 13]
 [68 97 57 47]]

[48 68]

[[56]
 [48]
 [34]
 [15]
 [37]]


Selecting in Boolean values

In [279]:
names=np.array(['bob','aly','alvin','benedict','aly'])

print(names=='aly')
print(names[names=='aly'])

[False  True False False  True]
['aly' 'aly']


fancy Indexing

In [280]:
#creating an empty array
arr2=np.empty((8,4))
print(arr2)

for i in range(8):
    arr2[i]=i
print(arr2)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [281]:
arr2[[0,2,4,6]]

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [282]:

arr2[[-3,-5]] 

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [283]:
arr5=np.arange(21)
arrmask=(arr5%5==0) # boolean true index
print(arr5[arrmask])

print(arr5[arrmask& (arr5>10)])

[ 0  5 10 15 20]
[15 20]


Array Transposition

In [284]:
arr1=np.arange(1,21).reshape(2,10)

print(arr1)
#arr.T is same as arr.transpose()
np.dot(arr1.T,arr1)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


array([[122, 134, 146, 158, 170, 182, 194, 206, 218, 230],
       [134, 148, 162, 176, 190, 204, 218, 232, 246, 260],
       [146, 162, 178, 194, 210, 226, 242, 258, 274, 290],
       [158, 176, 194, 212, 230, 248, 266, 284, 302, 320],
       [170, 190, 210, 230, 250, 270, 290, 310, 330, 350],
       [182, 204, 226, 248, 270, 292, 314, 336, 358, 380],
       [194, 218, 242, 266, 290, 314, 338, 362, 386, 410],
       [206, 232, 258, 284, 310, 336, 362, 388, 414, 440],
       [218, 246, 274, 302, 330, 358, 386, 414, 442, 470],
       [230, 260, 290, 320, 350, 380, 410, 440, 470, 500]])

In [285]:
print(arr1.transpose(0,1))
print()
print(arr1.transpose(1,0))

#transpose(0,1) leaves the array unchanged, while transpose(1,0) swaps the rows and columns.

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]


In [286]:
#3-D array
arr=np.arange(16).reshape(2,2,4)
print(arr)
print()
print()
print(arr.T)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [287]:
"""
Summary:
transpose(0,1,2): No change, same arrangement.
transpose(0,2,1): Swaps rows and columns within each block, changing the shape to (2, 4, 2).
transpose(1,0,2): Swaps the block order with the row order. With equal sizes (2 and 2), the shape stays (2, 2, 4) but the internal order is altered.
transpose(1,2,0): Rearranges so that rows come first, columns second, and blocks last, resulting in a shape of (2, 4, 2).
transpose(2,0,1): Moves the columns (original axis 2) to the front, giving a shape of (4, 2, 2).
transpose(2,1,0): Reverses the axes order completely, also resulting in (4, 2, 2).
Each permutation reorganizes the data differently, which can be useful for aligning dimensions for certain operations or for interfacing with libraries that expect data in a particular order.
"""

#swaps n axes
arr.transpose(0,2,1)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [288]:
#swap axes method to swap 2 axes
arr.swapaxes(0,2)


array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])