In [20]:
#numpy is implemented in C, so it is faster than python
#numpy uses vectorization, which is a way to compute operations on entire arrays instead of individual elements
#numpy does not use loops, so it is faster than python
#numpy is used for numerical operations and data analysis
#numpy is used for linear algebra, fourier transform, and random number capabilities
#numpy is used for operations on arrays and matrices
#numpy is used for operations on multidimensional arrays
#this is the reason why machine learning libraries are implemented in NumPy

In [1]:
#comparing '+' operator in python and numpy
import numpy as np

a=[1,2,3]
b=[4,5,6]
print(a+b)
#in the list, '+' operator concatenates the two lists
print()

#arithmetic operations are applied to individual elements in the array
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
#in the numpy array, '+' operator adds the two arrays element-wise

[1, 2, 3, 4, 5, 6]

[5 7 9]


In [2]:
#VARIOUS AIRTHMETIC OPERATIONS(ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION, MODULUS, EXPONENTIATION)
#Condition- both arrays should have same shape
print(a-b)
print(a+b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

[-3 -3 -3]
[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[  1  32 729]


In [3]:
#comparing list and numpy array multiplication
a1=[1,2,3]
print(a*3) # repeat the list 3 times


a2=np.array([1,2,3])
a2=a2*3  # multiply each element by 3
print(a2)

[3 6 9]
[3 6 9]


In [4]:
#Repeat and Tile(Functions)
#Repeat- repeat the indivdual elements of whole array one by one
#Tile- repeat the array along the specified axis
arr1=np.array([1,2,3])
arr2=np.repeat(arr1,3)
print(arr2)

print()

arr3=np.tile(arr1,3)
print(arr3)

print()
#can also be repeated in two dimentional form
arr4=np.random.randint(1,10,(3,3))
arr5=np.tile(arr4,3)
print(arr5)

[1 1 1 2 2 2 3 3 3]

[1 2 3 1 2 3 1 2 3]

[[2 4 6 2 4 6 2 4 6]
 [7 3 2 7 3 2 7 3 2]
 [5 7 2 5 7 2 5 7 2]]


In [5]:
#COMPARISON OPERATORS(returns a boolean array)
arr6=np.array([1,2,3])
print(arr6<2)

[ True False False]


In [6]:
#universal functions operate element-wise on the array

arr7 = np.array([1, 2, 3])

print(f"Square roots of {arr7}: {np.sqrt(arr7)}")  # Square root of each element
print(f"Exponential (e^x) of {arr7}: {np.exp(arr7)}")  # e raised to the power of each element
print(f"Natural log (ln) of {arr7}: {np.log(arr7)}")  # Natural logarithm of each element
print(f"Sine of {arr7} (radians): {np.sin(arr7)}")  # Sine of each element (in radians)
print(f"Cosine of {arr7} (radians): {np.cos(arr7)}")  # Cosine of each element (in radians)
print(f"Tangent of {arr7} (radians): {np.tan(arr7)}")  # Tangent of each element (in radians)
print(f"Arc sine (inverse sine) of {arr7}: {np.arcsin(arr7)}")  # Inverse sine (result in radians)
print(f"Arc cosine (inverse cosine) of {arr7}: {np.arccos(arr7)}")  # Inverse cosine (result in radians)
print(f"Arc tangent (inverse tangent) of {arr7}: {np.arctan(arr7)}")  # Inverse tangent (result in radians)
print(f"Hyperbolic sine of {arr7}: {np.sinh(arr7)}")  # Hyperbolic sine of each element
print(f"Hyperbolic cosine of {arr7}: {np.cosh(arr7)}")  # Hyperbolic cosine of each element
print(f"Hyperbolic tangent of {arr7}: {np.tanh(arr7)}")  # Hyperbolic tangent of each element
print(f"Inverse hyperbolic sine of {arr7}: {np.arcsinh(arr7)}")  # Inverse hyperbolic sine
print(f"Inverse hyperbolic cosine of {arr7}: {np.arccosh(arr7)}")  # Inverse hyperbolic cosine
print(f"Inverse hyperbolic tangent of {arr7}: {np.arctanh(arr7)}")  # Inverse hyperbolic tangent
print(f"Rounded values of {arr7}: {np.round(arr7)}")  # Rounds each element to the nearest integer
print(f"Floor values (round down) of {arr7}: {np.floor(arr7)}")  # Rounds down to the previous integer
print(f"Ceiling values (round up) of {arr7}: {np.ceil(arr7)}")  # Rounds up to the next integer
print(f"Absolute values of {arr7}: {np.abs(arr7)}")  # Absolute value of each element

Square roots of [1 2 3]: [1.         1.41421356 1.73205081]
Exponential (e^x) of [1 2 3]: [ 2.71828183  7.3890561  20.08553692]
Natural log (ln) of [1 2 3]: [0.         0.69314718 1.09861229]
Sine of [1 2 3] (radians): [0.84147098 0.90929743 0.14112001]
Cosine of [1 2 3] (radians): [ 0.54030231 -0.41614684 -0.9899925 ]
Tangent of [1 2 3] (radians): [ 1.55740772 -2.18503986 -0.14254654]
Arc sine (inverse sine) of [1 2 3]: [1.57079633        nan        nan]
Arc cosine (inverse cosine) of [1 2 3]: [ 0. nan nan]
Arc tangent (inverse tangent) of [1 2 3]: [0.78539816 1.10714872 1.24904577]
Hyperbolic sine of [1 2 3]: [ 1.17520119  3.62686041 10.01787493]
Hyperbolic cosine of [1 2 3]: [ 1.54308063  3.76219569 10.067662  ]
Hyperbolic tangent of [1 2 3]: [0.76159416 0.96402758 0.99505475]
Inverse hyperbolic sine of [1 2 3]: [0.88137359 1.44363548 1.81844646]
Inverse hyperbolic cosine of [1 2 3]: [0.         1.3169579  1.76274717]
Inverse hyperbolic tangent of [1 2 3]: [inf nan nan]
Rounded valu

C:\Users\bened\AppData\Local\Temp\ipykernel_28936\1355882767.py:11: RuntimeWarning: invalid value encountered in arcsin
  print(f"Arc sine (inverse sine) of {arr7}: {np.arcsin(arr7)}")  # Inverse sine (result in radians)
C:\Users\bened\AppData\Local\Temp\ipykernel_28936\1355882767.py:12: RuntimeWarning: invalid value encountered in arccos
  print(f"Arc cosine (inverse cosine) of {arr7}: {np.arccos(arr7)}")  # Inverse cosine (result in radians)
C:\Users\bened\AppData\Local\Temp\ipykernel_28936\1355882767.py:19: RuntimeWarning: divide by zero encountered in arctanh
  print(f"Inverse hyperbolic tangent of {arr7}: {np.arctanh(arr7)}")  # Inverse hyperbolic tangent
C:\Users\bened\AppData\Local\Temp\ipykernel_28936\1355882767.py:19: RuntimeWarning: invalid value encountered in arctanh
  print(f"Inverse hyperbolic tangent of {arr7}: {np.arctanh(arr7)}")  # Inverse hyperbolic tangent


In [7]:
#non universal functions  (returns single answer and not an array)


arr8 = np.array([1, 2, 3, 4, 5, 6])

print(f"Sum of all elements in {arr8}: {np.sum(arr8)}")  # Adds up all elements
print(f"Minimum element in {arr8}: {np.min(arr8)}")  # Finds the smallest element
print(f"Maximum element in {arr8}: {np.max(arr8)}")  # Finds the largest element
print(f"Variance of all elements in {arr8}: {np.var(arr8)}")  # Measures how spread out the elements are
print(f"Product of all elements in {arr8}: {np.prod(arr8)}")  # Multiplies all elements together
print(f"Cumulative sum of all elements in {arr8}: {np.cumsum(arr8)}")  # Running sum at each position
print(f"Cumulative product of all elements in {arr8}: {np.cumprod(arr8)}")  # Running product at each position
print(f"Unique elements in {arr8}: {np.unique(arr8)}")  # Lists distinct elements (no duplicates)

print(f"Mean of all elements in {arr8}: {np.mean(arr8)}")  # Average of all elements
print(f"Median of all elements in {arr8}: {np.median(arr8)}")  # Middle value when sorted
print(f"Standard deviation of all elements in {arr8}: {np.std(arr8)}")  # Spread of elements from the mean
print(f"Index of maximum element in {arr8}: {np.argmax(arr8)}")  # Position of the largest element
print(f"Index of minimum element in {arr8}: {np.argmin(arr8)}")  # Position of the smallest element


Sum of all elements in [1 2 3 4 5 6]: 21
Minimum element in [1 2 3 4 5 6]: 1
Maximum element in [1 2 3 4 5 6]: 6
Variance of all elements in [1 2 3 4 5 6]: 2.9166666666666665
Product of all elements in [1 2 3 4 5 6]: 720
Cumulative sum of all elements in [1 2 3 4 5 6]: [ 1  3  6 10 15 21]
Cumulative product of all elements in [1 2 3 4 5 6]: [  1   2   6  24 120 720]
Unique elements in [1 2 3 4 5 6]: [1 2 3 4 5 6]
Mean of all elements in [1 2 3 4 5 6]: 3.5
Median of all elements in [1 2 3 4 5 6]: 3.5
Standard deviation of all elements in [1 2 3 4 5 6]: 1.707825127659933
Index of maximum element in [1 2 3 4 5 6]: 5
Index of minimum element in [1 2 3 4 5 6]: 0


Statistical Methods()

In [8]:
#Statistical methods( USED ON A instance of numpy array(nd array object))


#x.mean() - returns the mean of the array
#x.std() - returns the standard deviation of the array
#x.var() - returns the variance of the array
#x.min() - returns the minimum value of the array
#x.max() - returns the maximum value of the array
#x.sum() - returns the sum of the array
#x.prod() - returns the product of the array
#x.cumsum() - returns the cumulative sum of the array
#x.cumprod() - returns the cumulative product of the array
#x.argmin() - returns the index of the minimum value of the array
#x.argmax() - returns the index of the maximum value of the array

x=np.array([1,2,3,4,5,6])
print(x.mean())

print(x.std())
print(x.var())
print(x.min())
print(x.max())
print(x.cumsum())

3.5
1.707825127659933
2.9166666666666665
1
6
[ 1  3  6 10 15 21]


In [9]:
#Reshaping the array

x=np.arange(1,7)
print(x)

#specifying rows and columns
print(x.reshape(2,3))
print()


#Specfying only the row or the column
print(x.reshape(-1,1))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [10]:
#Statistical methods for each row or each column
#axis=0: The function is applied down each column (i.e., it computes a statistic for each column by combining values from each row).
#axis=1: The function is applied across each row (i.e., it computes a statistic for each row by combining values from each column).

x=x.reshape(2,3)
print(x.mean(axis=1))# row mean

print(x.mean(axis=0)) # column mean

[2. 5.]
[2.5 3.5 4.5]


In [11]:
#using seed

import numpy as np

# Set the random seed to ensure reproducibility
np.random.seed(123)

# Generate an array of 5 random numbers between 0 and 1
random_numbers = np.random.rand(5)   #uniform distribution
print("Random numbers with seed 123:", random_numbers)

# Reset the seed to generate the same sequence again
np.random.seed(123)
print("Random numbers with seed 123 (again):", np.random.rand(5))

Random numbers with seed 123: [0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
Random numbers with seed 123 (again): [0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


In [12]:
#Random numbers in numpy

#using seed will generate fixed random number when generating random number values



#random integer between ( low,high)
arr=np.random.randint(1,11)
print(arr)
print('\n\n')

arr1=np.random.randint(1,11)

arr2=np.random.rand(1,11)# Generate an array of 10 random numbers between 0 and 1

print(arr1)
print()
print(arr2)



#program to demo the use of random numbers( will print 10 atleast once)
while True:
    a=np.random.randint(1,11)
    print(a)
    if(a==10):
        break

10



7

[[0.41092437 0.5796943  0.13995076 0.40101756 0.62731701 0.32415089
  0.24475928 0.69475518 0.5939024  0.63179202 0.44025718]]
5
8
3
5
9
1
8
10


In [13]:
# to generate random numbers arary of a particular size: use the keyword argument size

print(np.random.randint(1,11,size=10))              

[4 5 7 2 6 7 3 2 9 4]


<h1>MATRIX OPERATIONS</h1>


In [14]:
#
A=np.array([0,1,2,3]).reshape(2,2)
B=np.random.randint(0,4,size=4).reshape(2,2)

print(A)
print()
print(B)



[[0 1]
 [2 3]]

[[2 1]
 [0 3]]


Dot product of a matrix

In [15]:
print(A.dot(B))

# OR
print()
print(np.dot(A,B))


#this means that the dot is both method and a function of the np module


[[ 0  3]
 [ 4 11]]

[[ 0  3]
 [ 4 11]]


Transpose

In [16]:
#Transpose is both a function and a method
print(np.transpose(A))

print()
print(A.transpose())

[[0 2]
 [1 3]]

[[0 2]
 [1 3]]


Inverse of a matrix

In [17]:
print(np.linalg.inv(A))

[[-1.5  0.5]
 [ 1.   0. ]]


determinant of a matrix

In [18]:
np.linalg.det(A)

-2.0

eigen vectors and eigen values

In [21]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.56155281,  3.56155281]), eigenvectors=array([[-0.87192821, -0.27032301],
       [ 0.48963374, -0.96276969]]))